# Generated by Django 5.1.5 on 2025-03-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shorturl_expiration_date_shorturl_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
